"""Rename Column

Revision ID: 04b03b8df3bd
Revises: 3e403863733c
Create Date: 2024-06-19 13:34:49.241498

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '04b03b8df3bd'
down_revision: Union[str, None] = '3e403863733c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('representation', sa.Column('is_pwr_viewable', sa.Boolean(), nullable=True))
    op.drop_column('representation', 'is_pbyc_viewable')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('representation', sa.Column('is_pbyc_viewable', sa.BOOLEAN(), autoincrement=False, nullable=True))
    op.drop_column('representation', 'is_pwr_viewable')
    # ### end Alembic commands ###
