"""Initial Revision

Revision ID: 3e403863733c
Revises: 
Create Date: 2024-06-13 17:52:24.176257

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3e403863733c'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('plugins',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('pypi_url', sa.String(), nullable=True),
    sa.Column('dsl', sa.String(), nullable=True),
    sa.Column('doc', sa.String(), nullable=True),
    sa.Column('icon', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_plugins_id'), 'plugins', ['id'], unique=False)
    op.create_index(op.f('ix_plugins_name'), 'plugins', ['name'], unique=False)
    op.create_table('projects',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('project_class', sa.String(), nullable=True),
    sa.Column('parent_id', sa.Integer(), nullable=True),
    sa.Column('output_url', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('is_template', sa.Boolean(), nullable=True),
    sa.Column('is_deleted', sa.Boolean(), nullable=True),
    sa.Column('engine_url', sa.Boolean(), nullable=True),
    sa.Column('file_upload', sa.Boolean(), nullable=True),
    sa.Column('audio_upload', sa.Boolean(), nullable=True),
    sa.Column('has_credentials', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_projects_id'), 'projects', ['id'], unique=False)
    op.create_index(op.f('ix_projects_name'), 'projects', ['name'], unique=False)
    op.create_table('tags',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_tags_id'), 'tags', ['id'], unique=False)
    op.create_index(op.f('ix_tags_name'), 'tags', ['name'], unique=False)
    op.create_table('templates',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('project_class', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('engine_url', sa.Boolean(), nullable=True),
    sa.Column('file_upload', sa.Boolean(), nullable=True),
    sa.Column('audio_upload', sa.Boolean(), nullable=True),
    sa.Column('has_credentials', sa.Boolean(), nullable=True),
    sa.Column('verified', sa.Boolean(), nullable=True),
    sa.Column('sort', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_templates_id'), 'templates', ['id'], unique=False)
    op.create_index(op.f('ix_templates_name'), 'templates', ['name'], unique=False)
    op.create_table('users',
    sa.Column('oid', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('email', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('oid')
    )
    op.create_index(op.f('ix_users_oid'), 'users', ['oid'], unique=False)
    op.create_table('analytics_logs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('project_id', sa.Integer(), nullable=True),
    sa.Column('user_id', sa.String(), nullable=True),
    sa.Column('representation_name', sa.String(), nullable=True),
    sa.Column('data', sa.JSON(), nullable=True),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.oid'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_analytics_logs_id'), 'analytics_logs', ['id'], unique=False)
    op.create_index(op.f('ix_analytics_logs_name'), 'analytics_logs', ['name'], unique=False)
    op.create_index(op.f('ix_analytics_logs_project_id'), 'analytics_logs', ['project_id'], unique=False)
    op.create_index(op.f('ix_analytics_logs_user_id'), 'analytics_logs', ['user_id'], unique=False)
    op.create_table('dev_chat_messages',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('session_id', sa.String(), nullable=True),
    sa.Column('project_id', sa.Integer(), nullable=True),
    sa.Column('sender_id', sa.String(), nullable=True),
    sa.Column('sender', sa.Enum('user', 'bot', name='chat_user_type'), nullable=True),
    sa.Column('type', sa.Enum('instruction', 'feedback', 'thought', 'output', 'start', 'dsl_state', 'end', 'error', 'representation_edit', 'files', name='chat_message_type'), nullable=True),
    sa.Column('message', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('special_link', sa.String(), nullable=True),
    sa.Column('pbyc_comments', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_dev_chat_messages_id'), 'dev_chat_messages', ['id'], unique=False)
    op.create_index(op.f('ix_dev_chat_messages_project_id'), 'dev_chat_messages', ['project_id'], unique=False)
    op.create_table('exports',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('project_id', sa.Integer(), nullable=True),
    sa.Column('sandbox_responsecode', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_exports_id'), 'exports', ['id'], unique=False)
    op.create_index(op.f('ix_exports_project_id'), 'exports', ['project_id'], unique=False)
    op.create_table('output_chat_messages',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('session_id', sa.String(), nullable=True),
    sa.Column('sender_id', sa.String(), nullable=True),
    sa.Column('project_id', sa.Integer(), nullable=True),
    sa.Column('sender', sa.Enum('user', 'bot', name='output_user_type'), nullable=True),
    sa.Column('type', sa.Enum('instruction', 'feedback', 'thought', 'output', 'callback', 'debug', 'start', 'end', 'error', name='output_message_type'), nullable=True),
    sa.Column('message', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('special_link', sa.String(), nullable=True),
    sa.Column('pbyc_comments', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_output_chat_messages_id'), 'output_chat_messages', ['id'], unique=False)
    op.create_index(op.f('ix_output_chat_messages_project_id'), 'output_chat_messages', ['project_id'], unique=False)
    op.create_table('project_has_credentials',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('project_id', sa.Integer(), nullable=True),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('mandatory', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_project_has_credentials_id'), 'project_has_credentials', ['id'], unique=False)
    op.create_index(op.f('ix_project_has_credentials_project_id'), 'project_has_credentials', ['project_id'], unique=False)
    op.create_table('representation',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('type', sa.String(), nullable=True),
    sa.Column('text', sa.String(), nullable=True),
    sa.Column('project_id', sa.Integer(), nullable=True),
    sa.Column('is_editable', sa.Boolean(), nullable=True),
    sa.Column('sort_order', sa.Integer(), nullable=True),
    sa.Column('is_pbyc_viewable', sa.Boolean(), nullable=True),
    sa.Column('is_user_viewable', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_representation_id'), 'representation', ['id'], unique=False)
    op.create_index(op.f('ix_representation_name'), 'representation', ['name'], unique=False)
    op.create_index(op.f('ix_representation_project_id'), 'representation', ['project_id'], unique=False)
    op.create_table('template_has_credentials',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('template_id', sa.Integer(), nullable=True),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('mandatory', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['template_id'], ['templates.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_template_has_credentials_id'), 'template_has_credentials', ['id'], unique=False)
    op.create_index(op.f('ix_template_has_credentials_template_id'), 'template_has_credentials', ['template_id'], unique=False)
    op.create_table('template_has_plugins',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('template_id', sa.Integer(), nullable=True),
    sa.Column('plugin_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['plugin_id'], ['plugins.id'], ),
    sa.ForeignKeyConstraint(['template_id'], ['templates.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_template_has_plugins_id'), 'template_has_plugins', ['id'], unique=False)
    op.create_index(op.f('ix_template_has_plugins_plugin_id'), 'template_has_plugins', ['plugin_id'], unique=False)
    op.create_index(op.f('ix_template_has_plugins_template_id'), 'template_has_plugins', ['template_id'], unique=False)
    op.create_table('template_has_tags',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('template_id', sa.Integer(), nullable=True),
    sa.Column('tag_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['tag_id'], ['tags.id'], ),
    sa.ForeignKeyConstraint(['template_id'], ['templates.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_template_has_tags_id'), 'template_has_tags', ['id'], unique=False)
    op.create_index(op.f('ix_template_has_tags_tag_id'), 'template_has_tags', ['tag_id'], unique=False)
    op.create_index(op.f('ix_template_has_tags_template_id'), 'template_has_tags', ['template_id'], unique=False)
    op.create_table('users_has_projects',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('oid', sa.String(), nullable=True),
    sa.Column('project_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['oid'], ['users.oid'], ),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_has_projects_id'), 'users_has_projects', ['id'], unique=False)
    op.create_index(op.f('ix_users_has_projects_oid'), 'users_has_projects', ['oid'], unique=False)
    op.create_index(op.f('ix_users_has_projects_project_id'), 'users_has_projects', ['project_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_users_has_projects_project_id'), table_name='users_has_projects')
    op.drop_index(op.f('ix_users_has_projects_oid'), table_name='users_has_projects')
    op.drop_index(op.f('ix_users_has_projects_id'), table_name='users_has_projects')
    op.drop_table('users_has_projects')
    op.drop_index(op.f('ix_template_has_tags_template_id'), table_name='template_has_tags')
    op.drop_index(op.f('ix_template_has_tags_tag_id'), table_name='template_has_tags')
    op.drop_index(op.f('ix_template_has_tags_id'), table_name='template_has_tags')
    op.drop_table('template_has_tags')
    op.drop_index(op.f('ix_template_has_plugins_template_id'), table_name='template_has_plugins')
    op.drop_index(op.f('ix_template_has_plugins_plugin_id'), table_name='template_has_plugins')
    op.drop_index(op.f('ix_template_has_plugins_id'), table_name='template_has_plugins')
    op.drop_table('template_has_plugins')
    op.drop_index(op.f('ix_template_has_credentials_template_id'), table_name='template_has_credentials')
    op.drop_index(op.f('ix_template_has_credentials_id'), table_name='template_has_credentials')
    op.drop_table('template_has_credentials')
    op.drop_index(op.f('ix_representation_project_id'), table_name='representation')
    op.drop_index(op.f('ix_representation_name'), table_name='representation')
    op.drop_index(op.f('ix_representation_id'), table_name='representation')
    op.drop_table('representation')
    op.drop_index(op.f('ix_project_has_credentials_project_id'), table_name='project_has_credentials')
    op.drop_index(op.f('ix_project_has_credentials_id'), table_name='project_has_credentials')
    op.drop_table('project_has_credentials')
    op.drop_index(op.f('ix_output_chat_messages_project_id'), table_name='output_chat_messages')
    op.drop_index(op.f('ix_output_chat_messages_id'), table_name='output_chat_messages')
    op.drop_table('output_chat_messages')
    op.drop_index(op.f('ix_exports_project_id'), table_name='exports')
    op.drop_index(op.f('ix_exports_id'), table_name='exports')
    op.drop_table('exports')
    op.drop_index(op.f('ix_dev_chat_messages_project_id'), table_name='dev_chat_messages')
    op.drop_index(op.f('ix_dev_chat_messages_id'), table_name='dev_chat_messages')
    op.drop_table('dev_chat_messages')
    op.drop_index(op.f('ix_analytics_logs_user_id'), table_name='analytics_logs')
    op.drop_index(op.f('ix_analytics_logs_project_id'), table_name='analytics_logs')
    op.drop_index(op.f('ix_analytics_logs_name'), table_name='analytics_logs')
    op.drop_index(op.f('ix_analytics_logs_id'), table_name='analytics_logs')
    op.drop_table('analytics_logs')
    op.drop_index(op.f('ix_users_oid'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_templates_name'), table_name='templates')
    op.drop_index(op.f('ix_templates_id'), table_name='templates')
    op.drop_table('templates')
    op.drop_index(op.f('ix_tags_name'), table_name='tags')
    op.drop_index(op.f('ix_tags_id'), table_name='tags')
    op.drop_table('tags')
    op.drop_index(op.f('ix_projects_name'), table_name='projects')
    op.drop_index(op.f('ix_projects_id'), table_name='projects')
    op.drop_table('projects')
    op.drop_index(op.f('ix_plugins_name'), table_name='plugins')
    op.drop_index(op.f('ix_plugins_id'), table_name='plugins')
    op.drop_table('plugins')
    # ### end Alembic commands ###
